### ISSUE TITLE
LLNL example fails

### ISSUE THREAD

**Issue by liamtoney** [uafgeotools/pysep#17]
It's apparently the fault of `getwaveform.py`.

```console
(sln) ldtoney@coyote:~/REPOSITORIES/pysep$ check_getwaveform.bash 
10 events in check_getwaveform.bash (index 0 to 9)
checking 1 events in check_getwaveform.bash (index 9 to 9)
Running example iex = 11
WARNING using event data from the IRIS catalog
Traceback (most recent call last):
  File "run_getwaveform.py", line 99, in <module>
    ev_info.get_events_client()
  File "/home/ldtoney/REPOSITORIES/pysep/getwaveform.py", line 494, in get_events_client
    self.get_event_object()
  File "/home/ldtoney/REPOSITORIES/pysep/getwaveform.py", line 451, in get_event_object
    starttime = self.otime - self.sec_before_after_event,
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
diff: HOYA/HOYA_all_filenames: No such file or directory
9 WARNING: file1 and file2 differ
file1: getwaveform_saved/check_filenames/HOYA_all_filenames
file2: HOYA/HOYA_all_filenames
```

**Comment by liamtoney** [comment]
It's worth noting that the command
```console
(sln) ldtoney@coyote:~/REPOSITORIES/pysep$ python run_getwaveform.py
```
works perfectly on my *coyote* setup.

**Comment by bch0w** [comment]
The LLNL gathering has been rewritten in the latest version of PySEP and should work the same as data gathering for non-LLNL data
