### ISSUE TITLE
chinook conflict

### ISSUE THREAD

**Issue by rmodrak** [uafgeotools/pysep#19]
Just a warning that obspy and pysep conflict with the foss toolchain on chinook.

```
>>> module load lang/Python/3.5.2-foss-2016b
>>> pip install numpy obspy
>>> python -c "import obspy"
```

```
Traceback (most recent call last):
  File "/home/rmodrak/virtual/axisem_postprocess/lib/python3.5/site-packages/obspy/core/util/libnames.py", line 94, in _load_cdll
    cdll = ctypes.CDLL(str(libpath))
  File "/usr/local/pkg/lang/Python/3.5.2-foss-2016b/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libimf.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rmodrak/virtual/axisem_postprocess/lib/python3.5/site-packages/obspy/__init__.py", line 59, in <module>
    read.__doc__ % make_format_plugin_table("waveform", "read", numspaces=4)
  File "/home/rmodrak/virtual/axisem_postprocess/lib/python3.5/site-packages/obspy/core/util/base.py", line 521, in make_format_plugin_table
    func = buffered_load_entry_point(*ep_list)
  File "/home/rmodrak/virtual/axisem_postprocess/lib/python3.5/site-packages/obspy/core/util/misc.py", line 644, in buffered_load_entry_point
    _ENTRY_POINT_CACHE[hash_str] = load_entry_point(dist, group, name)
  File "/home/rmodrak/virtual/axisem_postprocess/lib/python3.5/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/rmodrak/virtual/axisem_postprocess/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/rmodrak/virtual/axisem_postprocess/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/rmodrak/virtual/axisem_postprocess/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/rmodrak/virtual/axisem_postprocess/lib/python3.5/site-packages/obspy/io/mseed/core.py", line 21, in <module>
    from . import (util, InternalMSEEDError, ObsPyMSEEDFilesizeTooSmallError,
  File "/home/rmodrak/virtual/axisem_postprocess/lib/python3.5/site-packages/obspy/io/mseed/util.py", line 24, in <module>
    from .headers import (ENCODINGS, ENDIAN, FIXED_HEADER_ACTIVITY_FLAGS,
  File "/home/rmodrak/virtual/axisem_postprocess/lib/python3.5/site-packages/obspy/io/mseed/headers.py", line 22, in <module>
    __clibmseed = _load_cdll("mseed")
  File "/home/rmodrak/virtual/axisem_postprocess/lib/python3.5/site-packages/obspy/core/util/libnames.py", line 97, in _load_cdll
    raise ImportError(msg)
ImportError: Could not load shared library "libmseed_Linux_64bit_py35.cpython-35m-x86_64-linux-gnu.so".

 libimf.so: cannot open shared object file: No such file or directory
```

**Comment by rmodrak** [comment]
A workaround is to use the intel toolchain, ie `module load lang/Python/3.5.2-pic-intel-2016b`.  Unfortunately, however,  this workaround may cause SPECFEM2D/3D/3D_GLOBE/AxiSEM  to no longer work.

**Comment by bch0w** [comment]
With the upcoming Chinook upgrade this issue has been solved and PySEP works as expected on their new RHEL OS
